name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Generate app keystore
      run: |
        echo "${{ secrets.JKS_BASE64 }}" | base64 -d > keystore
        echo "storeFile=keystore" > signing.properties
        echo "storePassword=${{ secrets.JKS_STORE_PASS }}" >> signing.properties
        echo "keyPassword=${{ secrets.JKS_KEY_PASS }}" >> signing.properties
        echo "keyAlias=${{ secrets.JKS_KEY_ALIAS }}" >> signing.properties

    - name: Update App name
      run: sed -i 's/Material Files/Files/g' app/src/main/res/values/strings.xml

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
